security:
    # Registrando el hash de las contraseñas
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Cliente:
            algorithm: bcrypt

    # Proveedores de usuarios
    providers:
        users_in_memory: { memory: null }
        database_users:
            entity:
                class: App\Entity\Cliente
                property: mail

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: database_users  # para usar la base de datos
            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\LoginSuccessHandler  # Si es cierto el login salta el handler
            logout:
                path: app_logout
                target: app_login

    # Jerarquía de roles
    role_hierarchy:
        ROLE_ADMIN: ROLE_VET
        ROLE_VET: ROLE_USER

    # Control de acceso
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/vet, roles: ROLE_VET }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/historial/add, roles: ROLE_VET }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }


# Configuración para el entorno de test
when@test:
    security:
        password_hashers:
            # Por defecto, los hashers de contraseñas consumen muchos recursos y tiempo. Esto es importante para generar contraseñas seguras.
            # En las pruebas, sin embargo, los hashes seguros no son importantes, desperdician recursos e incrementan los tiempos de prueba.
            # Lo siguiente reduce el factor de trabajo a los valores más bajos posibles.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valor más bajo posible para bcrypt
                time_cost: 3 # Valor más bajo posible para argon
                memory_cost: 10 # Valor más bajo posible para argon
